name: CI CD Pipeline - DrViki

on:
  push:
    branches: [ main ]

jobs:
  build-test-push-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/drviki-app:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (optional)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image (tagged with IMAGE_NAME)
        run: |
          docker build -t $IMAGE_NAME ./app
          docker image ls $IMAGE_NAME

      - name: Run container and test /health
        run: |
          # run image tagged with $IMAGE_NAME, map container 8088 -> runner 8088
          docker run -d --name drviki-ci -p 8088:8088 $IMAGE_NAME
          sleep 3
          # test the health endpoint
          curl -v --retry 5 --retry-delay 1 --max-time 10 http://localhost:8088/health
          docker rm -f drviki-ci

      - name: Push image to DockerHub
        run: docker push $IMAGE_NAME

      - name: Check if SSH deployment is configured
        id: check_ssh
        run: |
          if [ -n "${{ secrets.SSH_HOST }}" ]; then
            echo "ssh_configured=true" >> $GITHUB_OUTPUT
          else
            echo "ssh_configured=false" >> $GITHUB_OUTPUT
          fi

      - name: Deploy to remote host via SSH
        if: steps.check_ssh.outputs.ssh_configured == 'true'
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            docker pull $IMAGE_NAME
            docker rm -f drviki-app || true
            docker run -d --name drviki-app -p 8088:8088 --restart unless-stopped $IMAGE_NAME
